### ISSUE TITLE
Double clicking in the file open dialog to open a file draws on the canvas

### ISSUE THREAD

**Issue by btzy** [btzy/circuit-playground#10]
To reproduce:
1) Select an element from the toolbox using the primary mouse button
2) Draw something on the canvas (so that opening a file will launch a new instance)
3) Press Ctrl-O
4) Double click a file to open
5) Original canvas has a pixel drawn at the location that was double clicked

Single click, then press the "Open" button does not cause this issue.

**Comment by xsot** [comment]
Cannot reproduce on my machine. Could be a Windows-specific bug.

**Comment by btzy** [comment]
It appears to be a bug with file dialogs on Windows.  Will try solving by modifying NFD code.
