### ISSUE TITLE
File dialogs launched by button bar are unresponsive

### ISSUE THREAD

**Issue by xsot** [btzy/circuit-playground#12]
They seem to respond to keyboard events but not mouse events.

**Comment by btzy** [comment]
This is probably due to SDL_CaptureMouse() being turned on by MainWindow prior to invoking the file dialog.

**Comment by btzy** [comment]
This might be fixed by 622889f2bc395d7704d0dd1f5fbcd9ddcef3da33.

**Comment by xsot** [comment]
I can confirm that it has been fixed.
